name: MySQL database
env:
  MYSQL_DATABASE : team20
  MYSQL_USER : root
  MYSQL_PASSWORD : rootroot
  MYSQL_HOST : mysql-master
  NODE_ENV: test
on:
  push:
    branches: [ main ]

jobs:
  ci:
    runs-on: ubuntu-latest
    container :
      image: node:15.5.0-alpine
    services:
      mysql-master :
        image: mysql:8.0
        env:
          MYSQL_DATABASE: ${{ env.MYSQL_DATABASE }}
          MYSQL_USER : ${{ env.MYSQL_USER}}
          MYSQL_PASSWORD : ${{ env.MYSQL_PASSWORD}}
          MYSQL_ROOT_PASSWORD : ${{ env.MYSQL_PASSWORD}}
        options: >-
          --name = mysql-master
          --health-cmd = "mysqladmin ping"
          --health-interval = 10s
          --health-timeout=5s
          --health-retries=3

        ports:
          - "3306:3306"

    steps:
      - uses: actions/checkout@v2

      - name: Set root password
        run: |
          mysqladmin -u root password rootroot
      - name: setup database
        run: mysql -u root -root -e "CREATE DATABASE IF NOT EXISTS team20;"
