name: Create MySQL database

on:
  push:
    branches: [ main ]

jobs:
  create-database:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: rootroot
          MYSQL_DATABASE: team20
        ports:
          - "3306:3306"

    steps:
      - uses: actions/checkout@v3

      - name: Create database
        run: |
          sudo systemctl start mysql
          sudo mysql_secure_installation
          mysql -u root -ppassword -e "CREATE DATABASE IF NOT EXISTS team20;"
